name: ci-workflow
on: 
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setando ambiente do node versão 22.18.0
        uses: actions/setup-node@v4
        with:
          node-version: v22.18
          cache: 'npm'
        run: npm ci
        run: npm run build --if-present
        run: npm test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/desafio-ci-fc:latest

